version: '3'
services:
  pe_on_fastapi:
    build:
      context: .
      dockerfile: containers/development/Dockerfile
    volumes:
      - .:/src
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true  # 環境によってホットリロードのために必要
    command: /bin/bash -c "poetry install && poetry run uvicorn pe_on_fastapi.main:app --host 0.0.0.0 --reload"
    networks:
      - my-network
networks:
  my-network:
    external: true
